# Generated by Django 6.0 on 2025-12-12 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('final_severity', models.CharField(choices=[('RED', 'แดง'), ('YELLOW', 'เหลือง'), ('GREEN', 'เขียว')], default='GREEN', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TriageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_severity', models.CharField(blank=True, max_length=10, null=True)),
                ('nurse_severity', models.CharField(blank=True, max_length=10, null=True)),
                ('model_name', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_result', to='queues.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'รอ'), ('CALLED', 'เรียกแล้ว'), ('DONE', 'เสร็จสิ้น'), ('CANCELLED', 'ยกเลิก')], default='WAITING', max_length=10)),
                ('priority', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='queues.visit')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rr', models.IntegerField(blank=True, null=True, verbose_name='RR')),
                ('pr', models.IntegerField(blank=True, null=True, verbose_name='PR')),
                ('sys_bp', models.IntegerField(blank=True, null=True, verbose_name='Systolic BP')),
                ('dia_bp', models.IntegerField(blank=True, null=True, verbose_name='Diastolic BP')),
                ('bt', models.FloatField(blank=True, null=True, verbose_name='BT (°C)')),
                ('o2sat', models.IntegerField(blank=True, null=True, verbose_name='O₂ Sat')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='queues.visit')),
            ],
        ),
    ]
