# Generated by Django 6.0 on 2025-12-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=13, unique=True, verbose_name='เลขบัตรประชาชน')),
                ('hn', models.CharField(blank=True, max_length=20, null=True, verbose_name='HN')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทร')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='วันเกิด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
